name: Telegram notifyProduct Bot Workflow

on:
  push:
    branches:
      - main
      - fix/refactor_workflow

  workflow_dispatch:  
  # schedule:
  #   - cron: '0 * * * *'
   
jobs:
  fetch-products:
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Ensure database directory exists
        run: mkdir -p database
      
      - name: Run writeJson.py
        run: python writeJson.py

      - uses: actions/download-artifact@v5
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
        
      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: my_file.json
      #     retention-days: 5
          
      # - name: Run fetchProducts.py
      #   run: python fetchProducts.py
      
      # - name: Run fetch_fbMarketplace.py
      #   run: python fetch_fbMarketplace.py
