name: Telegram notifyProduct Bot Workflow

on:
  push:
    branches:
      - main
      - fix/refactor_workflow

  workflow_dispatch:  
  # schedule:
  #   - cron: '0 * * * *'
   
jobs:
  fetch-products:
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Ensure database directory exists
        run: mkdir -p database
      
      - name: Run writeJson.py
        run: python writeJson.py

      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: my_file.json
      #     retention-days: 5

      - name: Get previous workflow run
        id: prev
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'telegramBot-workflow.yml',
              branch: 'fix/refactor_workflow',
              status: 'completed',
              per_page: 2
            });
            const previousRun = runs.data.workflow_runs.find(run => run.id !== context.runId);
            return previousRun ? previousRun.id : null;

      - name: Debug previous run
        run: 'echo "Previous run id: ${{ steps.prev.outputs.result }}"'

      - name: Download artifact from previous run
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.prev.outputs.result }}
          name: my-artifact
          path: ./prev-artifact

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./prev-artifact
          retention-days: 5
