name: Telegram notifyProduct Bot Workflow

on:
  push:
    branches:
      - main
      - fetch_fb-marketplace

  workflow_dispatch:  
  # schedule:
  #   - cron: '*/30 * * * *' # run each 30 minute
   
jobs:
  fetch-products:
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Ensure database directory exists
        run: mkdir -p database
  
      - name: Restore database cache
        uses: actions/cache@v4
        with:
          path: database/ebay_found_items.db
          key: ebay-db-cache-${{ runner.os }}
          restore-keys: |
            ebay-db-cache-${{ runner.os }}
  
      # - name: Run fetchProducts.py
      #   run: python fetchProducts.py
      
      - name: Run fetch_fbMarketplace.py
        run: python fetch_fbMarketplace.py
  
      - name: Save database cache
        uses: actions/cache@v4
        with:
          path: database/ebay_found_items.db
          key: ebay-db-cache-${{ runner.os }}
          restore-keys: |
            ebay-db-cache-${{ runner.os }}