name: Telegram notifyProduct Bot Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  
# schedule:
  # - cron: '*/30 * * * *' # run each 30 minute
   
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Download database artifact # detta funkar inte?????? den hittar inte artifakten
        uses: actions/download-artifact@v4
        with:
          name: database
          path: database/
        continue-on-error: true
      
      - name: Run fetchProducts.py script
        run: python fetchProducts.py
      
      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: database
          path: database/ebay_found_items.db
          retention-days: 90
