name: Telegram notifyProduct Bot Workflow

on:
  push:
    branches:
      - main
      - fix/refactor_workflow

  workflow_dispatch:  
  # schedule:
  #   - cron: '0 * * * *'
   
jobs:
  fetch-products:
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Ensure database directory exists
        run: mkdir -p database
      
      - name: Run writeJson.py
        run: python writeJson.py

      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: my_file.json
      #     retention-days: 5

      - name: Get previous successful run id
        id: prev
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'telegramBot-workflow.yml',
              status: 'success',
              per_page: 5
            })

            const previousRun = runs.data.workflow_runs
              .find(run => run.id !== context.runId)

            if (!previousRun) {
              core.setFailed("No previous successful run found")
            }

            return previousRun.id

      - name: Download artifact from previous run
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.prev.outputs.result }}
          name: my-artifact
          path: ./prev-artifact      

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./prev-artifact/my_file.json
          retention-days: 5