name: productScraper Workflow
on:
  push:
    branches:
      - fix/ebay_marketplace
    #  - main

  workflow_dispatch:  
#  schedule:
    # - cron: '0 */3 * * *'
   
jobs:
  fetch-products:
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ebay_marketplace.py
        run: python fetch/ebay/ebay_marketplace.py
        
      - name: Run fb_marketplace.py
        run: python fetch/facebook/fb_marketplace.py

      - name: Run blocket_marketplace.py
        run: python fetch/blocket/blocket_marketplace.py
